### PR TITLE
Add support for more IDEs

### PR DESCRIPTION
**Pull request by Jonathing**
This time, I added support for AppCode (a macOS exclusive IDE), MPS, DataGrip, and Rider.

I also changed the name of the Java IDE from "IntelliJ" to "IntelliJ IDEA" because all the IDEs are essentially IntelliJ and "IDEA" give the Java IDE a little boost lol.

Chao

### CODE REVIEW

**Comment by Jonathing** [comment]
Now I probably should've added some way to put in the icons for those IDEs, but I couldn't find out how anywhere in the code, or it was just too compact for me to read it all correctly.

**Review by s5bug — DISMISSED** [review]
Icons are stored in the RPC app. Please upload the icons to this PR from the branding page.

**Comment by Jonathing** [comment]
Will do when I can

**Comment by Jonathing** [comment]
I couldn't find where to put the application images anywhere in the code, and the package.scala file has changed so I can't add IDE's manually.

**Comment by s5bug** [comment]
@JonathanTheInsane Not in the code, but in this PR. Also, IDE names are now determined by application info.

The images go into RPC but it's not fun going through rarely-used ides logos and upscaling them to 1024x1024 to add them.

**Comment by s5bug** [comment]
Inactive

**Pull request closed without merging**
