### PR TITLE
Add support for PyCharm Edu

### PR DESCRIPTION
**Pull request by Jonathing**
because that also seems to be a thing.

### CODE REVIEW

**Comment by s5bug** [comment]
I forgot about PyCharm Edu! When I get home I'll add the respective icons. Not home due to the Oceanside fires currently.

**Comment by s5bug** [comment]
I also need to pull and release a zip update for this when I get home.

**Comment by Jonathing** [comment]
Thanks fam. I'll hit you up if I can add anything else interesting. Also, what exactly are the libraries you use to get this thing working in IntelliJ? I have Discord-RPC-Scala loaded but I'm still getting a few errors, and I'm interested in looking into your code and seeing how I can help. Thanks!

**Comment by s5bug** [comment]
Are you using Scala and do you have the Scala SDK installed? (2.12.4)

Also, update 1.4.1 is being reviewed by the JetBrains team.

**Comment by Jonathing** [comment]
@TsundereBug I got it working. However I get errors when I try to build it lol

**Pull request merged**
